[package]
name = "openttd_gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = "0.36"
openttd_video = { path = "../openttd_video" }
thiserror = "1.0"
log = "0.4"

[dev-dependencies]
env_logger = "0.11"

[features]
default = []
ttf = ["sdl2/ttf"]
