[package]
name = "openttd_cli"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
openttd_savegame = { path = "../openttd_savegame" }
openttd_video = { path = "../openttd_video" }
ctrlc = "3"

[features]
default = []
sdl2 = ["openttd_video/sdl2"]
