[package]
name = "openttd_video"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
thiserror = "1"
sdl2 = { version = "0.36", optional = true }

[features]
default = ["stub"]
stub = []
sdl2 = ["dep:sdl2"]
